import { Event } from '@/types/event';

// 2026년 실제 확인된 행사 데이터 (2026년 5월 11일 기준)
// expected_visitors = 일 최대 동시관람객 수 기준
// ※ (미확정) 표기 항목은 역대 패턴 기반 예상 일정
export const SAMPLE_EVENTS: Event[] = [

  // ── 5월 ─────────────────────────────────
  {
    id: '8',
    title: '서울재즈페스티벌 2026',
    category: 'festival',
    date_start: '2026-05-22',
    date_end: '2026-05-24',
    venue: '올림픽공원 88잔디마당 · KSPO DOME',
    location: '서울',
    district: '잠실',
    expected_visitors: 30000,
    description: '자넬 모네, 에즈라 콜렉티브, 도겸·승관(세븐틴), 에픽하이 등 · 멜론티켓 단독',
    source_url: 'https://ticket.melon.com/performance/index.htm?prodId=212811',
  },

  // ── 6월 ─────────────────────────────────
  {
    id: '21',
    title: 'Weverse Con Festival 2026',
    category: 'festival',
    date_start: '2026-06-06',
    date_end: '2026-06-07',
    venue: '올림픽공원 KSPO DOME · 88잔디마당',
    location: '서울',
    district: '잠실',
    expected_visitors: 20000,
    description: 'BTS·SEVENTEEN·LE SSERAFIM 등 30팀+ 출연 멀티스테이지 K-POP 페스티벌',
    source_url: 'https://weverseconfestival.weverse.io/en/',
  },
  {
    id: '1',
    title: 'BTS 월드투어 ARIRANG - 부산',
    category: 'concert',
    date_start: '2026-06-12',
    date_end: '2026-06-13',
    venue: '부산 아시아드 주경기장',
    location: '부산',
    district: '아시아드',
    expected_visitors: 50000,
    description: '방탄소년단 월드투어 부산 공연 (6/13 데뷔기념일) · NOL 티켓 단독 판매',
    source_url: 'https://tickets.interpark.com/goods/26005547',
  },
  {
    id: '25',
    title: '월드 DJ 페스티벌 20주년',
    category: 'festival',
    date_start: '2026-06-13',
    date_end: '2026-06-14',
    venue: '과천 서울랜드',
    location: '경기',
    district: '과천',
    expected_visitors: 20000,
    description: '국내 최대 EDM 페스티벌 20주년 기념',
    source_url: 'https://www.songkick.com/festivals/365443-world-dj/id/42893744-world-dj-festival-2026',
  },
  {
    id: '22',
    title: 'SEVENTEEN CARAT LAND 팬미팅',
    category: 'concert',
    date_start: '2026-06-20',
    date_end: '2026-06-21',
    venue: '인천 아시아드주경기장',
    location: '인천',
    district: '아시아드',
    expected_visitors: 50000,
    description: '세븐틴 10주년 팬미팅 · 양일 합산 10만명 규모',
    source_url: 'https://tickets.interpark.com/contents/notice/detail/13328',
  },
  {
    id: '23',
    title: '부산원아시아페스티벌(BOF) 10주년',
    category: 'festival',
    date_start: '2026-06-27',
    date_end: '2026-06-28',
    venue: '부산 아시아드주경기장',
    location: '부산',
    district: '아시아드',
    expected_visitors: 30000,
    description: 'K-POP 멀티 아티스트 페스티벌 10주년',
    source_url: 'https://mobile.busan.com/view/newsunicollvill/view.php?code=2026040315341460860',
  },

  // ── 7월 ─────────────────────────────────
  {
    id: '24',
    title: 'BLACKPINK DEADLINE 월드투어 - 고양',
    category: 'concert',
    date_start: '2026-07-05',
    date_end: '2026-07-06',
    venue: '고양종합운동장 주경기장',
    location: '경기',
    district: '고양',
    expected_visitors: 40000,
    description: '블랙핑크 월드투어 고양 공연 · 양일 76,489명 규모',
    source_url: 'https://tickets.interpark.com/goods/25006132',
  },
  {
    id: '26',
    title: 'LE SSERAFIM TOUR PUREFLOW - 인천',
    category: 'concert',
    date_start: '2026-07-11',
    date_end: '2026-07-12',
    venue: '인천 인스파이어 아레나',
    location: '인천',
    district: '영종도',
    expected_visitors: 18000,
    description: '르세라핌 월드투어 인천 공연',
    source_url: 'https://www.heraldmuse.com/article/10732238',
  },
  {
    id: '19',
    title: '워터밤 서울 2026',
    category: 'festival',
    date_start: '2026-07-24',
    date_end: '2026-07-26',
    venue: '고양 KINTEX 야외 글로벌 스테이지',
    location: '경기',
    district: '고양',
    expected_visitors: 35000,
    description: '국내 최대 물 축제 · 19세 이상 관람가',
    source_url: 'https://tickets.interpark.com/goods/25018467',
  },
  {
    id: '9',
    title: '인천 펜타포트 락 페스티벌 2026',
    category: 'festival',
    date_start: '2026-07-31',
    date_end: '2026-08-02',
    venue: '송도달빛축제공원',
    location: '인천',
    district: '송도',
    expected_visitors: 40000,
    description: '제21회 · NOL 인터파크 단독 판매',
    source_url: 'https://tickets.interpark.com/goods/26006159',
  },

  // ── 8월 ─────────────────────────────────
  {
    id: '20',
    title: 'BIGBANG BIGSHOW: REBORN 월드투어 - 서울',
    category: 'concert',
    date_start: '2026-08-01',
    date_end: '2026-08-01',
    venue: '서울 (장소 미정)',
    location: '서울',
    district: undefined,
    expected_visitors: 50000,
    description: '빅뱅 20주년 기념 월드투어 서울 개막 (G-Dragon·태양·대성) · 장소·예매처 추후 공지',
    source_url: 'https://www.koreaherald.com/article/10686832',
  },
  {
    id: '18',
    title: 'aespa LIVE TOUR SYNK : COMPLæXITY - 서울',
    category: 'concert',
    date_start: '2026-08-07',
    date_end: '2026-08-08',
    venue: '고척스카이돔',
    location: '서울',
    district: '고척',
    expected_visitors: 20000,
    description: '2026-27 aespa 월드투어 서울 공연 · 예매처 추후 공지 (Weverse 프리세일 예정)',
    source_url: 'https://weverse.io/aespa/notice/35057?hl=ko',
  },

  // ── 9월 ─────────────────────────────────
  {
    id: '27',
    title: 'Coldplay Music of the Spheres - 서울',
    category: 'concert',
    date_start: '2026-09-12',
    date_end: '2026-09-13',
    venue: '잠실올림픽주경기장',
    location: '서울',
    district: '잠실',
    expected_visitors: 60000,
    description: '콜드플레이 내한 공연 · 잠실 올림픽주경기장 양일',
    source_url: 'https://www.dudle.co.kr/2026-%EC%BD%9C%EB%93%9C%ED%94%8C%EB%A0%88%EC%9D%B4-%EB%82%B4%ED%95%9C-%EC%9D%BC%EC%A0%95%EA%B3%BC-%EA%B3%B5%EC%97%B0-%EC%9E%A5%EC%86%8C-%EC%99%84%EB%B2%BD-%EA%B0%80%EC%9D%B4%EB%93%9C/',
  },

  // ── 10월 ─────────────────────────────────
  {
    id: '28',
    title: 'Post Malone The BIG Stadium Tour - 고양',
    category: 'concert',
    date_start: '2026-10-02',
    date_end: '2026-10-02',
    venue: '고양종합운동장 주경기장',
    location: '경기',
    district: '고양',
    expected_visitors: 50000,
    description: '포스트 말론 내한 공연',
    source_url: 'https://tickets.interpark.com/goods/26004944',
  },
  {
    id: '5',
    title: '한화 서울세계불꽃축제 (※ 미확정)',
    category: 'fireworks',
    date_start: '2026-10-03',
    date_end: '2026-10-03',
    venue: '여의도한강공원',
    location: '서울',
    district: '여의도',
    expected_visitors: 1000000,
    description: '※ 공식 발표 전 — 역대 패턴(10월 첫째 주 토요일) 기반 예상일. 매년 100만명+ 방문',
  },
  {
    id: '29',
    title: 'EDC Korea 2026',
    category: 'festival',
    date_start: '2026-10-03',
    date_end: '2026-10-04',
    venue: '인천 인스파이어 리조트',
    location: '인천',
    district: '영종도',
    expected_visitors: 30000,
    description: '일렉트릭 데이지 카니발 코리아 · 개천절 연휴',
    source_url: 'https://korea.electricdaisycarnival.com/en/',
  },
  {
    id: '30',
    title: 'The Weeknd 현대카드 슈퍼콘서트 28 - 고양',
    category: 'concert',
    date_start: '2026-10-07',
    date_end: '2026-10-08',
    venue: '고양종합운동장 주경기장',
    location: '경기',
    district: '고양',
    expected_visitors: 50000,
    description: '위켄드 내한 · 양일 합산 10만명 규모 (현대카드 슈퍼콘서트)',
    source_url: 'https://www.newsis.com/view/NISX20260422_0003601040',
  },
  {
    id: '31',
    title: 'Charlie Puth 내한 공연 - 고양',
    category: 'concert',
    date_start: '2026-10-11',
    date_end: '2026-10-11',
    venue: '고양종합운동장 주경기장',
    location: '경기',
    district: '고양',
    expected_visitors: 40000,
    description: '찰리 푸스 단독 내한',
    source_url: 'https://www.newsis.com/view/NISX20260422_0003601040',
  },
  {
    id: '11',
    title: '부산 국제영화제 (BIFF)',
    category: 'festival',
    date_start: '2026-10-01',
    date_end: '2026-10-10',
    venue: '영화의전당',
    location: '부산',
    district: '해운대',
    expected_visitors: 30000,
    description: '※ 공식 일정 미확정 (역대 패턴 기준)',
    source_url: 'https://www.biff.kr',
  },
  {
    id: '13',
    title: 'KBO 한국시리즈 (※ 미확정)',
    category: 'sports',
    date_start: '2026-10-21',
    date_end: '2026-10-31',
    venue: '개최구장 미정',
    location: '서울',
    district: '잠실',
    expected_visitors: 25000,
    description: '※ 정규시즌 종료 후 확정. 예상 개최지: 잠실야구장',
    source_url: 'https://www.koreabaseball.com',
  },

  // ── 11월 ─────────────────────────────────
  {
    id: '6',
    title: '부산 광안리 불꽃축제 (※ 미확정)',
    category: 'fireworks',
    date_start: '2026-11-07',
    date_end: '2026-11-07',
    venue: '광안리해수욕장',
    location: '부산',
    district: '수영구',
    expected_visitors: 500000,
    description: '※ 공식 발표 전 — 역대 패턴(11월 첫째 주 토요일) 기반 예상일',
  },
];
