import { Event } from '@/types/event';

// 2026년 실제 확인된 행사 데이터 (2026년 5월 11일 기준)
// expected_visitors = 일 최대 동시관람객 수 기준
// ※ (미확정) 표기 항목은 역대 패턴 기반 예상 일정
export const SAMPLE_EVENTS: Event[] = [

  // ── 4월 (지난 행사 · 투표 샘플) ─────────────────────────
  {
    id: 'past1',
    slug: 'iu-hereh-encore-seoul-2026',
    title: '아이유 콘서트 HEREH 앙코르 (서울)',
    category: 'concert',
    date_start: '2026-04-19',
    date_end: '2026-04-20',
    venue: '고척스카이돔',
    location: '서울',
    district: '구로',
    expected_visitors: 24000,
    impact: 4,
    impact_basis: '전국 팬 이동 + 여성 팬층 강함',
    description: '아이유 HEREH 월드투어 서울 앙코르 공연 · 2일간 · 전석 매진',
  },

  // ── 5월 ─────────────────────────────────
  {
    id: '8',
    slug: 'seoul-jazz-festival-2026',
    title: '서울재즈페스티벌 2026',
    category: 'festival',
    date_start: '2026-05-22',
    date_end: '2026-05-24',
    venue: '올림픽공원 88잔디마당 · KSPO DOME',
    location: '서울',
    district: '잠실',
    expected_visitors: 30000,
    impact: 3,
    impact_basis: '20~30대 체류 수요',
    description: '자넬 모네, 에즈라 콜렉티브, 도겸·승관(세븐틴), 에픽하이 등 · 멜론티켓 단독',
    source_url: 'https://ticket.melon.com/performance/index.htm?prodId=212811',
  },

  // ── 6월 ─────────────────────────────────
  {
    id: '21',
    slug: 'weverse-con-festival-2026',
    title: 'Weverse Con Festival 2026',
    category: 'festival',
    date_start: '2026-06-06',
    date_end: '2026-06-07',
    venue: '올림픽공원 KSPO DOME · 88잔디마당',
    location: '서울',
    district: '잠실',
    expected_visitors: 20000,
    impact: 4,
    impact_basis: '글로벌 KPOP 팬 유입',
    description: "트리뷰트 아티스트 비(RAIN)를 포함해 엔하이픈, 르세라핌, 지코, 보이넥스트도어, 플레이브 등 30팀 출연 멀티스테이지 K-POP 페스티벌",
    source_url: 'https://weverseconfestival.weverse.io/en/',
  },
  {
    id: '1',
    slug: 'bts-arirang-busan-2026',
    title: 'BTS 월드투어 ARIRANG - 부산',
    category: 'concert',
    date_start: '2026-06-12',
    date_end: '2026-06-13',
    venue: '부산 아시아드 주경기장',
    location: '부산',
    district: '아시아드',
    expected_visitors: 50000,
    impact: 5,
    impact_basis: '해외팬·장기체류·초대형 팬덤',
    description: '방탄소년단 월드투어 부산 공연 (6/13 데뷔기념일) · NOL 티켓 단독 판매',
    source_url: 'https://tickets.interpark.com/goods/26005547',
  },
  {
    id: '25',
    slug: 'world-dj-festival-2026',
    title: '월드 DJ 페스티벌 20주년',
    category: 'festival',
    date_start: '2026-06-13',
    date_end: '2026-06-14',
    venue: '잠실체육단지',
    location: '서울',
    district: '잠실',
    expected_visitors: 20000,
    impact: 4,
    impact_basis: '20~30대 단체 이동',
    description: '국내 최대 EDM 페스티벌 20주년 기념',
    source_url: 'https://www.songkick.com/festivals/365443-world-dj/id/42893744-world-dj-festival-2026',
  },
  {
    id: '22',
    slug: 'seventeen-carat-land-2026',
    title: '세븐틴 CARAT LAND 팬미팅',
    category: 'concert',
    date_start: '2026-06-20',
    date_end: '2026-06-21',
    venue: '인천 아시아드주경기장',
    location: '인천',
    district: '아시아드',
    expected_visitors: 50000,
    impact: 4,
    impact_basis: '일본·동남아 팬 유입 강함',
    description: '세븐틴 10주년 팬미팅 · 양일 합산 10만명 규모',
    source_url: 'https://tickets.interpark.com/contents/notice/detail/13328',
  },
  {
    id: '23',
    slug: 'bof-10th-busan-2026',
    title: '부산원아시아페스티벌(BOF) 10주년',
    category: 'festival',
    date_start: '2026-06-27',
    date_end: '2026-06-28',
    venue: '부산 아시아드주경기장',
    location: '부산',
    district: '아시아드',
    expected_visitors: 30000,
    impact: 4,
    impact_basis: '관광 연계 체류 발생',
    description: 'K-POP 멀티 아티스트 페스티벌 10주년',
    source_url: 'https://tickets.interpark.com/contents/notice/detail/13676',
  },

  // ── 7월 ─────────────────────────────────
  {
    id: '24',
    slug: 'blackpink-deadline-goyang-2026',
    title: '블랙핑크 DEADLINE 월드투어 - 고양',
    category: 'concert',
    date_start: '2026-07-05',
    date_end: '2026-07-06',
    venue: '고양종합운동장 주경기장',
    location: '경기',
    district: '고양',
    expected_visitors: 40000,
    impact: 5,
    impact_basis: '해외팬 대규모 이동',
    description: '블랙핑크 월드투어 고양 공연 · 양일 76,489명 규모',
    source_url: 'https://tickets.interpark.com/goods/25006132',
  },
  {
    id: '26',
    slug: 'lesserafim-pureflow-incheon-2026',
    title: '르세라핌 PUREFLOW 투어 - 인천',
    category: 'concert',
    date_start: '2026-07-11',
    date_end: '2026-07-12',
    venue: '인천 인스파이어 아레나',
    location: '인천',
    district: '영종도',
    expected_visitors: 18000,
    impact: 4,
    impact_basis: '일본·아시아 팬덤 강세',
    description: '르세라핌 월드투어 인천 공연',
    source_url: 'https://weverse.io/lesserafim/notice/35577',
  },
  {
    id: '19',
    slug: 'waterbomb-seoul-2026',
    title: '워터밤 서울 2026',
    category: 'festival',
    date_start: '2026-07-24',
    date_end: '2026-07-26',
    venue: '고양 KINTEX 야외 글로벌 스테이지',
    location: '경기',
    district: '고양',
    expected_visitors: 35000,
    impact: 4,
    impact_basis: '단체·주말 체류 강함',
    description: '국내 최대 물 축제 · 19세 이상 관람가',
    source_url: 'https://tickets.interpark.com/goods/25018467',
  },
  {
    id: '9',
    slug: 'incheon-pentaport-2026',
    title: '인천 펜타포트 락 페스티벌 2026',
    category: 'festival',
    date_start: '2026-07-31',
    date_end: '2026-08-02',
    venue: '송도달빛축제공원',
    location: '인천',
    district: '송도',
    expected_visitors: 40000,
    impact: 3,
    impact_basis: '지방 관람객 이동',
    description: '제21회 · NOL 인터파크 단독 판매',
    source_url: 'https://tickets.interpark.com/goods/26006159',
  },

  // ── 8월 ─────────────────────────────────
  {
    id: '20',
    slug: 'bigbang-reborn-seoul-2026',
    title: '빅뱅 BIGSHOW: REBORN 월드투어 - 서울',
    category: 'concert',
    date_start: '2026-08-01',
    date_end: '2026-08-01',
    venue: '서울 (장소 미정)',
    location: '서울',
    district: undefined,
    expected_visitors: 50000,
    impact: 5,
    impact_basis: '세대 팬덤+해외 수요',
    description: '빅뱅 20주년 기념 월드투어 서울 개막 (G-Dragon·태양·대성) · 장소·예매처 추후 공지',
    source_url: 'https://www.koreaherald.com/article/10686832',
  },
  {
    id: '18',
    slug: 'aespa-synk-complexity-seoul-2026',
    title: '에스파 SYNK : COMPLæXITY 투어 - 서울',
    category: 'concert',
    date_start: '2026-08-07',
    date_end: '2026-08-08',
    venue: '고척스카이돔',
    location: '서울',
    district: '고척',
    expected_visitors: 20000,
    impact: 4,
    impact_basis: '글로벌 여성팬 강세',
    description: '에스파 2026-27 월드투어 서울 공연 · 예매처 추후 공지 (Weverse 프리세일 예정)',
    source_url: 'https://weverse.io/aespa/notice/35057?hl=ko',
  },

  // ── 9월 ─────────────────────────────────
  {
    id: '27',
    slug: 'coldplay-seoul-2026',
    title: '콜드플레이 Music of the Spheres - 서울',
    category: 'concert',
    date_start: '2026-09-12',
    date_end: '2026-09-13',
    venue: '잠실올림픽주경기장',
    location: '서울',
    district: '잠실',
    expected_visitors: 60000,
    impact: 5,
    impact_basis: '해외·지방 체류 대형',
    description: '콜드플레이 내한 공연 · 잠실 올림픽주경기장 양일',
    source_url: 'https://www.dudle.co.kr/2026-%EC%BD%9C%EB%93%9C%ED%94%8C%EB%A0%88%EC%9D%B4-%EB%82%B4%ED%95%9C-%EC%9D%BC%EC%A0%95%EA%B3%BC-%EA%B3%B5%EC%97%B0-%EC%9E%A5%EC%86%8C-%EC%99%84%EB%B2%BD-%EA%B0%80%EC%9D%B4%EB%93%9C/',
  },

  // ── 10월 ─────────────────────────────────
  {
    id: '28',
    slug: 'post-malone-goyang-2026',
    title: '포스트 말론 The BIG Stadium Tour - 고양',
    category: 'concert',
    date_start: '2026-10-02',
    date_end: '2026-10-02',
    venue: '고양종합운동장 주경기장',
    location: '경기',
    district: '고양',
    expected_visitors: 50000,
    impact: 4,
    impact_basis: '수도권 숙박 수요 발생',
    description: '포스트 말론 내한 공연',
    source_url: 'https://tickets.interpark.com/goods/26004944',
  },
  {
    id: '5',
    slug: 'seoul-fireworks-2026',
    title: '한화 서울세계불꽃축제 (※ 미확정)',
    category: 'fireworks',
    date_start: '2026-10-03',
    date_end: '2026-10-03',
    venue: '여의도한강공원',
    location: '서울',
    district: '여의도',
    expected_visitors: 1000000,
    impact: 3,
    impact_basis: '서울 전역 이동량 증가',
    description: '※ 공식 발표 전 — 역대 패턴(10월 첫째 주 토요일) 기반 예상일. 매년 100만명+ 방문',
  },
  {
    id: '29',
    slug: 'edc-korea-2026',
    title: 'EDC Korea 2026',
    category: 'festival',
    date_start: '2026-10-03',
    date_end: '2026-10-04',
    venue: '인천 인스파이어 리조트',
    location: '인천',
    district: '영종도',
    expected_visitors: 30000,
    impact: 4,
    impact_basis: '체류형 EDM 팬덤',
    description: '일렉트릭 데이지 카니발 코리아 · 개천절 연휴',
    source_url: 'https://korea.electricdaisycarnival.com/en/',
  },
  {
    id: '30',
    slug: 'weeknd-supercon-goyang-2026',
    title: '더 위켄드 현대카드 슈퍼콘서트 28 - 고양',
    category: 'concert',
    date_start: '2026-10-07',
    date_end: '2026-10-08',
    venue: '고양종합운동장 주경기장',
    location: '경기',
    district: '고양',
    expected_visitors: 50000,
    impact: 5,
    impact_basis: '해외팬·커플 체류 강함',
    description: '위켄드 내한 · 양일 합산 10만명 규모 (현대카드 슈퍼콘서트)',
    source_url: 'https://tickets.interpark.com/contents/notice/detail/13790',
  },
  {
    id: '31',
    slug: 'charlie-puth-goyang-2026',
    title: '찰리 푸스 내한 공연 - 고양',
    category: 'concert',
    date_start: '2026-10-11',
    date_end: '2026-10-11',
    venue: '고양종합운동장 주경기장',
    location: '경기',
    district: '고양',
    expected_visitors: 40000,
    impact: 3,
    impact_basis: '주말 숙박 수요',
    description: '찰리 푸스 단독 내한',
    source_url: 'https://tickets.interpark.com/goods/26005759',
  },
  {
    id: '11',
    slug: 'biff-busan-2026',
    title: '부산 국제영화제 (BIFF)',
    category: 'festival',
    date_start: '2026-10-01',
    date_end: '2026-10-10',
    venue: '영화의전당',
    location: '부산',
    district: '해운대',
    expected_visitors: 30000,
    impact: 4,
    impact_basis: '업계 관계자 장기 체류',
    description: '※ 공식 일정 미확정 (역대 패턴 기준)',
    source_url: 'https://www.biff.kr',
  },
  {
    id: '13',
    slug: 'kbo-korean-series-2026',
    title: 'KBO 한국시리즈 (※ 미확정)',
    category: 'sports',
    date_start: '2026-10-21',
    date_end: '2026-10-31',
    venue: '개최구장 미정',
    location: '서울',
    district: '잠실',
    expected_visitors: 25000,
    impact: 4,
    impact_basis: '원정팬 이동 가능성',
    description: '※ 정규시즌 종료 후 확정. 예상 개최지: 잠실야구장',
    source_url: 'https://www.koreabaseball.com',
  },

  // ── 11월 ─────────────────────────────────
  {
    id: '6',
    slug: 'busan-fireworks-2026',
    title: '부산 광안리 불꽃축제 (※ 미확정)',
    category: 'fireworks',
    date_start: '2026-11-07',
    date_end: '2026-11-07',
    venue: '광안리해수욕장',
    location: '부산',
    district: '수영구',
    expected_visitors: 500000,
    impact: 4,
    impact_basis: '부산 숙박 수요 폭증',
    description: '※ 공식 발표 전 — 역대 패턴(11월 첫째 주 토요일) 기반 예상일',
  },

  // ════════════════════════════════════════════════════════
  // ── 추가 행사 (스포츠·이스포츠·문화 시즌)
  // ════════════════════════════════════════════════════════

  // ── 3월 (지난 행사) ──────────────────────────────────────
  {
    id: '32',
    slug: 'seoul-marathon-2026',
    title: '서울마라톤 2026 (동아마라톤)',
    category: 'sports',
    date_start: '2026-03-15',
    date_end: '2026-03-15',
    venue: '광화문광장 → 잠실올림픽주경기장',
    location: '서울',
    district: '광화문',
    expected_visitors: 30000,
    impact: 3,
    impact_basis: '전국 러너 이동 + 전날 숙박 수요',
    description: '제91회 동아마라톤 · 풀코스 3만명+ 참가 · 국내 최대 봄 마라톤 · 서울 도심 코스',
    source_url: 'https://www.donga-marathon.co.kr/',
  },

  // ── 4~6월 (한강 드론 라이트쇼 — 5회차 개별 날짜) ──────────
  {
    id: '33a',
    slug: 'hangang-drone-show-2026-r1',
    title: '한강 드론 라이트쇼 1회차',
    category: 'fireworks',
    date_start: '2026-04-10',
    date_end: '2026-04-10',
    venue: '여의도한강공원',
    location: '서울',
    district: '여의도',
    expected_visitors: 30000,
    impact: 1,
    impact_basis: '당일 방문 위주',
    description: '2026 한강 드론 라이트쇼 1회차 · 여의도한강공원 · 드론 라이트 쇼 20:30~20:45',
    source_url: 'https://hangang.seoul.go.kr/',
  },
  {
    id: '33b',
    slug: 'hangang-drone-show-2026-r2',
    title: '한강 드론 라이트쇼 2회차',
    category: 'fireworks',
    date_start: '2026-04-25',
    date_end: '2026-04-25',
    venue: '뚝섬한강공원',
    location: '서울',
    district: '뚝섬',
    expected_visitors: 30000,
    impact: 1,
    impact_basis: '숙박 전환 낮음',
    description: '2026 한강 드론 라이트쇼 2회차 · 뚝섬한강공원 · 드론 라이트 쇼 20:30~20:45',
    source_url: 'https://hangang.seoul.go.kr/',
  },
  {
    id: '33c',
    slug: 'hangang-drone-show-2026-r3',
    title: '한강 드론 라이트쇼 3회차',
    category: 'fireworks',
    date_start: '2026-05-05',
    date_end: '2026-05-05',
    venue: '잠실한강공원',
    location: '서울',
    district: '잠실',
    expected_visitors: 30000,
    impact: 1,
    impact_basis: '당일 방문 중심',
    description: '2026 한강 드론 라이트쇼 3회차 · 잠실한강공원 · 드론 라이트 쇼 20:30~20:45',
    source_url: 'https://hangang.seoul.go.kr/',
  },
  {
    id: '33d',
    slug: 'hangang-drone-show-2026-r4',
    title: '한강 드론 라이트쇼 4회차',
    category: 'fireworks',
    date_start: '2026-05-16',
    date_end: '2026-05-16',
    venue: '뚝섬한강공원',
    location: '서울',
    district: '뚝섬',
    expected_visitors: 30000,
    impact: 1,
    impact_basis: '숙박 영향 제한적',
    description: '2026 한강 드론 라이트쇼 4회차 · 뚝섬한강공원 · 드론 라이트 쇼 20:30~20:45',
    source_url: 'https://hangang.seoul.go.kr/',
  },
  {
    id: '33e',
    slug: 'hangang-drone-show-2026-r5',
    title: '한강 드론 라이트쇼 5회차',
    category: 'fireworks',
    date_start: '2026-06-05',
    date_end: '2026-06-05',
    venue: '뚝섬한강공원',
    location: '서울',
    district: '뚝섬',
    expected_visitors: 30000,
    impact: 1,
    impact_basis: '체류형 아님',
    description: '2026 한강 드론 라이트쇼 5회차 · 뚝섬한강공원 · 드론 라이트 쇼 20:30~20:45',
    source_url: 'https://hangang.seoul.go.kr/',
  },

  // ── 6~7월 ────────────────────────────────────────────────
  {
    id: '34a',
    slug: 'msi-2026-playin',
    title: '롤 MSI 2026 - 시즌 중간 세계대회 (플레이인)',
    category: 'esports',
    date_start: '2026-06-28',
    date_end: '2026-07-01',
    venue: '대전컨벤션센터(DCC) 제2전시장',
    location: '대전',
    district: '유성구',
    expected_visitors: 8000,
    impact: 4,
    impact_basis: '해외팬·관계자 장기 체류',
    description: 'MSI 2026 플레이인 · 해외 팀·팬 초반 입국 수요 · 금~일 포함 항공·숙박 동시 상승 · 장기체류 관광객 多',
    source_url: 'https://lolesports.com/ko-KR/news/msi-and-worlds-updates',
  },
  {
    id: '34b',
    slug: 'msi-2026-finals',
    title: '롤 MSI 2026 - 시즌 중간 세계대회 (결승주간)',
    category: 'esports',
    date_start: '2026-07-08',
    date_end: '2026-07-12',
    venue: '대전컨벤션센터(DCC) 제2전시장',
    location: '대전',
    district: '유성구',
    expected_visitors: 15000,
    impact: 5,
    impact_basis: '최고 체급 국제 팬덤',
    description: 'MSI 2026 결승주간 · Upper Final 7/9 · Lower Final 7/11 · Grand Final 7/12 · 결승 직관러·해외 코어팬·미디어 집중 · 대전 핵심 숙박 피크',
    source_url: 'https://lolesports.com/ko-KR/news/msi-and-worlds-updates',
  },
  {
    id: '35',
    slug: 'yeondeunghoe-2026',
    title: '연등회 2026 (UNESCO 무형유산)',
    category: 'festival',
    date_start: '2026-05-16',
    date_end: '2026-05-17',
    venue: '동국대 → 흥인지문 → 종로 → 조계사 일대',
    location: '서울',
    district: '종로',
    expected_visitors: 20000,
    impact: 3,
    impact_basis: '외국 관광객 유입 + 도심 체류',
    description: 'UNESCO 인류 무형문화유산 · 5/16 연등행렬 19:00~21:30(동국대→조계사) · 대동한마당 21:30~23:00 · 60개 단체 2만명+ 참가 · 무료',
    source_url: 'http://www.llf.or.kr/',
  },

  // ── 6월 ──────────────────────────────────────────────────
  {
    id: '37',
    slug: 'myk-festa-2026',
    title: 'MyK FESTA 2026',
    category: 'festival',
    date_start: '2026-06-25',
    date_end: '2026-06-28',
    venue: 'KINTEX + Sono Calm Goyang',
    location: '경기',
    district: '고양',
    expected_visitors: 30000,
    impact: 4,
    impact_basis: '산업+팬덤 복합 행사',
    description: '문체부·CJ ENM 주최 K컬처 엑스포 · KPOP 공연·체험·전시·B2B 상담회 4트랙 · ZEROBASEONE·RIIZE·TREASURE·HIGHLIGHT·EVNNE 등',
    source_url: 'https://www.mykfesta.com/kor/',
  },
  {
    id: '38',
    slug: 'hangang-triathlon-2026',
    title: '쉬엄쉬엄 한강 3종 축제 2026 (제3회)',
    category: 'sports',
    date_start: '2026-06-05',
    date_end: '2026-06-07',
    venue: '뚝섬한강공원 · 잠실한강공원',
    location: '서울',
    district: '뚝섬',
    expected_visitors: 5000,
    impact: 2,
    impact_basis: '참가자 중심 행사',
    description: '순위·기록 부담 없는 나만의 속도로 완주하는 수영·자전거·달리기 3종 축제 · 2025년 총 66만명 방문 · 참가비 3만원~',
    source_url: 'https://korean.visitseoul.net/events/2026-MyPace-Hangang-Festival/KOPdbivac',
  },
  {
    id: '39',
    slug: 'seoul-park-music-festival-2026',
    title: '서울 파크 뮤직 페스티벌 2026',
    category: 'festival',
    date_start: '2026-06-20',
    date_end: '2026-06-21',
    venue: '올림픽공원 88잔디마당 + 티켓링크 라이브 아레나',
    location: '서울',
    district: '잠실',
    expected_visitors: 20000,
    impact: 2,
    impact_basis: '주말 체류 일부 발생',
    description: '피크닉형 야외 음악 페스티벌\n록·인디·발라드·K-POP 대중적 라인업\n토 14:00~22:30 / 일 14:00~21:30\n1DAY 119,000원 · NOL티켓·네이버예약',
    source_url: 'https://pmf.co.kr/',
  },

  // ── 7월 ──────────────────────────────────────────────────
  {
    id: '40',
    slug: 'boryeong-mud-festival-2026',
    title: '보령머드축제 2026 (제29회)',
    category: 'festival',
    date_start: '2026-07-24',
    date_end: '2026-08-09',
    venue: '대천해수욕장 일원',
    location: '충남',
    district: '보령',
    expected_visitors: 300000,
    impact: 3,
    impact_basis: '여행형 숙박 수요',
    description: '제29회 · 17일간 · 드론라이트쇼·K-POP 슈퍼라이브 공연 · 머드체험존(일반·패밀리·워터파크·반려견) · 세계 최대 체험형 여름 축제 · 인근 숙박 완전 매진 패턴',
    source_url: 'https://www.mudfestival.or.kr/festival/view',
  },

  // ── 8~9월 ────────────────────────────────────────────────
  {
    id: '41',
    slug: 'lck-summer-finals-2026',
    title: '2026 LCK Finals - 롤 한국 프로리그 결승전',
    category: 'esports',
    date_start: '2026-09-12',
    date_end: '2026-09-13',
    venue: 'KSPO DOME',
    location: '서울',
    district: '잠실',
    expected_visitors: 15000,
    impact: 4,
    impact_basis: 'T1 진출 시 폭발적 수요',
    description: 'LoL 챔피언스 코리아 서머 파이널 · 9/12 결승 진출전 · 9/13 LCK 서머 결승전 · KSPO DOME 15,000석',
    source_url: 'https://www.inven.co.kr/webzine/news/?news=311696&site=lol',
  },
  // 발로란트 챔피언스 2026 → 중국 상하이 개최 (9/24~10/18), 국내 오프라인 참여 불가 → 제외
  // 롤드컵(Worlds) 2026 → 미국 LA·텍사스·뉴욕 개최 (10/15~11/14), 국내 참여 불가 → 제외
  {
    id: '44',
    slug: 'seoul-race-2026',
    title: '서울레이스 / 나이키 런 이벤트 2026',
    category: 'sports',
    date_start: '2026-10-18',
    date_end: '2026-10-18',
    venue: '여의도한강공원 일대',
    location: '서울',
    district: '여의도',
    expected_visitors: 25000,
    impact: 3,
    impact_basis: '러닝 크루 이동',
    description: '가을 시즌 러닝 이벤트 · 여의도 일대 참가자 2만명+ · 일정 및 참가 신청 공식 채널 확인',
    source_url: 'https://www.nike.com/kr',
  },
  {
    id: '45',
    slug: 'jtbc-seoul-marathon-2026',
    title: 'JTBC 서울마라톤 2026 (제마)',
    category: 'sports',
    date_start: '2026-11-01',
    date_end: '2026-11-01',
    venue: '상암월드컵공원 (출발) → 올림픽공원·여의도공원 (도착)',
    location: '서울',
    district: '상암',
    expected_visitors: 32000,
    impact: 3,
    impact_basis: '새벽 경기 전날 숙박',
    description: '국내 3대 메이저 마라톤 · 러닝 커뮤니티 성지급 행사 · 풀코스·10K · 전국 러너 + 해외 참가자 3만명+ · 참가비 풀 15만원 / 10K 10만원',
    source_url: 'https://marathon.jtbc.com/',
  },
  {
    id: '46',
    slug: 'seoul-lantern-festival-2026',
    title: '서울빛초롱축제 2026',
    category: 'festival',
    date_start: '2026-11-07',
    date_end: '2026-11-15',
    venue: '청계천 일대',
    location: '서울',
    district: '청계천',
    expected_visitors: 100000,
    impact: 2,
    impact_basis: '관광객 유입 중심',
    description: '청계천 전통 등 작품 전시 · 야간 관람 · 서울 도심 광화문·종로 숙박 수요↑',
    source_url: 'https://www.seoullanternfestival.com/',
  },
  {
    id: '47',
    slug: 'pubg-nations-cup-2026',
    title: 'PUBG 네이션스컵 2026 - 국가대표 올스타전',
    category: 'esports',
    date_start: '2026-06-23',
    date_end: '2026-06-28',
    venue: '장충체육관',
    location: '서울',
    district: '장충',
    expected_visitors: 5000,
    impact: 3,
    impact_basis: '24개국 글로벌 팬덤 이동',
    description: '배틀그라운드 국가대표 올스타전 · 2019년 이후 7년 만의 서울 개최 · 24개국 참가 · 서바이벌 스테이지 6/23~24 · 그랜드 파이널 6/26~28',
    source_url: 'https://pubg.com/ko/news/9993',
  },
];
